controller_frequency: 5.0

controller_patience: 3.0

 

planner_frequency: 1.0

planner_patience: 5.0

 

oscillation_timeout: 8.0

oscillation_distance: 0.3

obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.35, 0.33], [0.35, -0.33], [-0.35, -0.33], [-0.35, 0.33]]


base_global_planner: "global_planner/GlobalPlanner"
