global_costmap:
   global_frame: /map
   robot_base_frame: base_link
   update_frequency: 5.0
   static_map: true
   resolution: 0.05
   transform_tolerance: 1.0
   map_type: costmap
   plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
#     - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
     - {name: simplelayer,             type: "simple_layer_namespace::SimpleLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
   inflation_layer: 
      inflation_radius: 0.1
